### PR TITLE
[MCHANGES-451]  Remove items which were deprecated in 2.x

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by elharo — APPROVED** [review]

**Review by michael-o — CHANGES_REQUESTED** [review]
Summary has a grammatical typo

**Comment by slawekjaranowski** [comment]
> Summary has a grammatical typo

How should be?

**Comment by michael-o** [comment]
Remove items which were deprecated in 2.x

**Comment by slawekjaranowski** [comment]
@michael-o - summary fixed

**Review by michael-o — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #381

**Pull request merged**
