### PR TITLE
[MCHANGES-439] Deprecate useJql

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
we cen remove such preparing next major
and issue - MCHANGES-439?

**Comment by slawekjaranowski** [comment]
We should also fix documentation - https://maven.apache.org/plugins/maven-changes-plugin/examples/customizing-jira-report.html

**Comment by elharo** [comment]
good point on docs; done

**Review by slawekjaranowski — COMMENTED** [review]
I still think that we can simply remove, even more that is not used in code.

Simply users will have a warning that use not existing parameter,
with deprecated they will have warning abut deprecation,
so will be similar from user perspective.

**Comment by elharo** [comment]
What specifically do you want to remove? We shouldn't take out the parameter without a deprecation cycle because it likely still exists in some folks' poms.

**Comment by jira-importer** [comment]
Resolve #325

**Pull request merged**
