### PR TITLE
remove geronimo javamail

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by elharo** [comment]
Tests pass: https://builds.apache.org/job/maven-box/job/maven-changes-plugin/job/mail/

**Comment by michael-o** [comment]
Is there any compile time code here?
What das `mvn dependency:analyze` say?

**Comment by elharo** [comment]
Everything passes:

https://builds.apache.org/job/maven-box/job/maven-changes-plugin/job/mail/

At master:

```
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ maven-changes-plugin ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.cxf:cxf-api:jar:2.6.3:compile
[WARNING]    org.apache.xmlrpc:xmlrpc-common:jar:3.1.3:compile
[WARNING]    org.sonatype.aether:aether-util:jar:1.13.1:compile
[WARNING]    org.apache.maven:maven-settings-builder:jar:3.0.5:compile
[WARNING]    javax.ws.rs:jsr311-api:jar:1.1.1:compile
[WARNING]    org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[WARNING]    org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0:compile
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[WARNING]    org.apache.cxf:cxf-rt-transports-http:jar:2.6.3:compile
[WARNING]    org.sonatype.aether:aether-impl:jar:1.13.1:compile
[WARNING]    xml-apis:xml-apis:jar:1.3.04:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.codehaus.plexus:plexus-interpolation:jar:1.24:compile
[WARNING]    org.apache.geronimo.javamail:geronimo-javamail_1.4_provider:jar:1.7:compile
[WARNING]    org.apache.geronimo.javamail:geronimo-javamail_1.4_mail:jar:1.7:compile
[WARNING]    org.codehaus.plexus:plexus-mail-sender-javamail:jar:1.0-alpha-7:compile
[WARNING]    org.codehaus.plexus:plexus-mail-sender-simple:jar:1.0-alpha-7:compile
[WARNING]    commons-logging:commons-logging:jar:1.1.1:compile
[WARNING]    org.apache.maven.doxia:doxia-module-xhtml:jar:1.4:compile
[WARNING]    org.apache.httpcomponents:httpcore:jar:4.2.3:compile
[WARNING]    org.apache.httpcomponents:httpclient:jar:4.2.3:compile
[WARNING]    org.apache.maven:maven-compat:jar:3.0.5:test
[WARNING]    org.sonatype.aether:aether-connector-wagon:jar:1.13.1:test
[WARNING]    org.apache.maven.wagon:wagon-http:jar:2.4:test
```

and in this branch:

```
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ maven-changes-plugin ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.cxf:cxf-api:jar:2.6.3:compile
[WARNING]    org.apache.xmlrpc:xmlrpc-common:jar:3.1.3:compile
[WARNING]    javax.mail:mail:jar:1.4:compile
[WARNING]    org.sonatype.aether:aether-util:jar:1.13.1:compile
[WARNING]    org.apache.maven:maven-settings-builder:jar:3.0.5:compile
[WARNING]    javax.ws.rs:jsr311-api:jar:1.1.1:compile
[WARNING]    org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[WARNING]    org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0:compile
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[WARNING]    org.apache.cxf:cxf-rt-transports-http:jar:2.6.3:compile
[WARNING]    org.sonatype.aether:aether-impl:jar:1.13.1:compile
[WARNING]    xml-apis:xml-apis:jar:1.3.04:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.codehaus.plexus:plexus-interpolation:jar:1.24:compile
[WARNING]    org.codehaus.plexus:plexus-mail-sender-javamail:jar:1.0-alpha-7:compile
[WARNING]    org.codehaus.plexus:plexus-mail-sender-simple:jar:1.0-alpha-7:compile
[WARNING]    commons-logging:commons-logging:jar:1.1.1:compile
[WARNING]    org.apache.maven.doxia:doxia-module-xhtml:jar:1.4:compile
[WARNING]    org.apache.httpcomponents:httpcore:jar:4.2.3:compile
[WARNING]    org.apache.httpcomponents:httpclient:jar:4.2.3:compile
[WARNING]    org.apache.maven:maven-compat:jar:3.0.5:test
[WARNING]    org.sonatype.aether:aether-connector-wagon:jar:1.13.1:test
[WARNING]    org.apache.maven.wagon:wagon-http:jar:2.4:test
```

Looks like there's a lot more cleanup left to do after this PR.

**Comment by michael-o** [comment]
Here is the reason: https://maven.apache.org/plugins/maven-changes-plugin/examples/smtp-authentication.html

**Comment by elharo** [comment]
This is not the only mail dependency we have. Indeed it is not the only dependency that provides some of these classes. Can you locate the place where we're using these particular artifacts? I could not. 

These artifacts are quite old and don't seem to be actively maintained. Keeping them around seems risky.

**Comment by rmannibucau** [comment]
Side note: they are still maintained (and dev to be complete). Advance conf can be sometimes different from javax.mail when not specified but works well. We should probably rather drop javax.mail and keep our impl only IMHO, would simplify reviews and licensing work.

**Pull request closed without merging**
