### PR TITLE
new http

### PR DESCRIPTION
**Pull request by elharo**
Let's see what Jenkins makes of this.

### CODE REVIEW

**Comment by elharo** [comment]
Yep, this definitely causes the test to fail but only on JDK7:

org.apache.maven.plugin.MojoExecutionException: Couldn't resolve the skin.
	at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76)
Caused by: org.apache.maven.shared.transfer.artifact.resolve.ArtifactResolverException: Failed to read artifact descriptor for org.apache.maven.skins:maven-default-skin:jar:1.0
	at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76)
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven.skins:maven-default-skin:jar:1.0
	at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven.skins:maven-default-skin:pom:1.0 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version
	at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76)
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven.skins:maven-default-skin:pom:1.0 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version
Caused by: org.apache.maven.wagon.TransferFailedException: Received fatal alert: protocol_version
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version

**Comment by elharo** [comment]
https://www.baeldung.com/java-7-tls-v12

**Comment by michael-o** [comment]
Can you apply? -Djavax.net.debug=all

**Comment by michael-o** [comment]
We'd need either Azul Zulu or AdoptOpenJDK on Jenkins.

**Comment by elharo** [comment]
Does AdoptOpenJDK ship a Java 7 VM?

**Comment by elharo** [comment]
Also, looks like that might have to be done by a Jenkins administrator? I.e. we don't configure it in this repo as we might do with Travis?

**Comment by michael-o** [comment]
My bad, it does not. But Azul does: https://www.azul.com/downloads/zulu-community/?&version=java-7-lts&architecture=x86-64-bit&package=jdk

**Pull request closed without merging**
